### 环境变量定义
@baseUrl = http://localhost:3000
@contentType = application/json

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI5NmQ3NmIwYS0yYzc4LTQ2ODItODQ0MS03Mjg3ZGRmNGI5MjQiLCJpYXQiOjE3NDYwODgwMzAsImV4cCI6MTc0NjA4ODA2MH0.P-KeR1FuT47JLeLqASbkbp50l_oa3igc6uBC5eO0TVU

@refresh_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNzQ2MDg2MTc2NjUwIiwiaWF0IjoxNzQ2MDg4MDEyLCJleHAiOjE3NDYxNzQ0MTJ9.xkW6UnD0PUKwN3HVoX5hTxTT0nVWNbdPCVLgTslSnf0

### [1] 用户注册
# @name signup
POST {{baseUrl}}/sign-up
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd123!"
}

### [2a] 用户登录
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "testuse@example.com",
    "password": "P@ssw0rd23!"
}

### [2b] 用户登录
# @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd123!"
}

### [3] 访问受保护数据 Access
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}

### [4] 验证令牌有效性 Access
GET {{baseUrl}}/api/verify-token
Authorization: Bearer {{access_token}}

### [5] 刷新访问令牌 Refresh
# @name refresh
POST {{baseUrl}}/api/refresh-token
Content-Type: {{contentType}}

{
    "refreshToken": "{{refresh_token}}"
}


### [6] 使用新令牌访问数据
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}

### [7] 注销操作
DELETE {{baseUrl}}/logout
Authorization: Bearer {{access_token}}

### [8] 失效令牌测试（应在注销后返回401）
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}