### 环境变量定义
@baseUrl = http://localhost:3000
@contentType = application/json

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxNzQ2Mjc5OTU0MDE2IiwiZW1haWwiOiJ0ZXN0dXNlckBleGFtcGxlLmNvbSIsImp0aSI6IjExYWUyNWFjLWYwM2ItNDRkZC1hM2E2LTExZDg0MzQ2ODdjNyIsImlhdCI6MTc0NjI3OTk4MywiZXhwIjoxNzQ2MjgwODgzfQ.inqf6gEV--Mj-PQUB4QwDFP8rp7ZT2fm9m6zTr4fO1s
@refresh_token = 2ce622b2-39f5-4bd0-8b2a-36d7f5d2f96c

### [1] 用户注册
# @name signup
POST {{baseUrl}}/auth/sign-up
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd123!"
}

### [2b] 用户登录
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd123!"
}

### [3] 访问受保护数据 Access
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}

### [4] 验证令牌有效性 Access
GET {{baseUrl}}/api/verify-token
Authorization: Bearer {{access_token}}

### [5] 刷新访问令牌 Refresh
# @name refresh
POST {{baseUrl}}/api/refresh-token
Content-Type: {{contentType}}

{
    "refreshToken": "{{refresh_token}}"
}


### [6] 使用新令牌访问数据
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}

### [7] 注销操作
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{access_token}}
Content-Type: {{contentType}}

{
    "refreshToken": "{{refresh_token}}"
}

### [8] 失效令牌测试（应在注销后返回401）
GET {{baseUrl}}/api/protected-data
Authorization: Bearer {{access_token}}