@baseUrl = http://localhost:3000
@contentType = application/json

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiI3MGMyYzVkOC1hZmJmLTQyNDgtOWE1OC03ZmFkNWQwN2M2ODEiLCJpYXQiOjE3NDY4OTEwODYsImV4cCI6MTc0Njg5MTk4Nn0.7MaaIAV7lt5xJMX_AWHc40U6bpb3WGVioa5cXLRh2bo
@refresh_token = 254654ec-8e6d-489c-83d1-fbd983133fee

### [2a] 用户登录
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd123!"
}

### [2b] 用户登录
# @name login
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "ohnohello@example.com",
    "password": "WoXiHuanLinGuZi"
}

### [3a] 创建任务
POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "task_name": "Complete Project",
  "content": "Finish backend integration",
  "status": "pending",
  "deadline": "2023-12-31",
  "priority": "high",
  "category_name": "Work"
}

### [3b] 创建任务
POST {{baseUrl}}/api/tasks
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "task_name": "Testing Project 4",
  "content": "Ohnoohohohohohno",
  "status": "pending",
  "deadline": "2023-2-28",
  "priority": "low",
  "category_name": "game"
}

### [4] 查看任务
GET {{baseUrl}}/api/tasks
Authorization: Bearer {{access_token}}

### [5] 查看单个任务
GET {{baseUrl}}/api/tasks/6
Authorization: Bearer {{access_token}}

### [6] 更新任务状态
PUT {{baseUrl}}/api/tasks/6/deadline
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "deadline": "2023-3-28"
}

### [7] 删除任务
DELETE {{baseUrl}}/api/tasks/3
Authorization: Bearer {{access_token}}

### [8] 更改别人的任务
PUT {{baseUrl}}/api/tasks/1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "completed"
}

### [9] 注销操作
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{access_token}}
Content-Type: {{contentType}}

{
    "refreshToken": "{{refresh_token}}"
}