@baseUrl = http://localhost:3000
@contentType = application/json

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiI5NWVhY2ExZi03YWUwLTQ0NmEtYjk5Yi0zYWNkNmNiYTM2NjQiLCJpYXQiOjE3NDY4OTc5MzAsImV4cCI6MTc0Njg5ODgzMH0.Uwe3pXEwWieW2-QyGy-3myVFtDeQFhiGA2nKP6s1aDs
@refresh_token = 254654ec-8e6d-489c-83d1-fbd983133fee


### [1] Get All Timer Records
GET {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

###

### [2] Create a Timer Record
POST {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_id": 1,
  "date": "2025-05-10",
  "timer_duration": 3600
}

###

### [3] Get Timer Records for Non-Existent User
GET {{baseUrl}}/api/timers
Authorization: Bearer {{invalid_access_token}}
Content-Type: application/json

###

### [4] Create Timer Record with Missing Fields
POST {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_id": 1,
  "date": "2025-05-10"
}

###

### [5] Create Timer Record for Unauthorized User
POST {{baseUrl}}/api/timer
Authorization: Bearer {{invalid_access_token}}
Content-Type: application/json

{
  "user_id": 999,
  "date": "2025-05-10",
  "timer_duration": 3600
}