@baseUrl = http://localhost:3000
@contentType = application/json

@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoidGVzdHVzZXJAZXhhbXBsZS5jb20iLCJqdGkiOiIxYzQ0NzVhOC1jYmYwLTQxMGUtOGFiNi03NzczYTYzNDRjMTgiLCJpYXQiOjE3NDY4OTkyMTYsImV4cCI6MTc0NjkwMDExNn0.j2m7j9gbsoQ54uHxavyukoZl84fDiBjGZ45MX578Nkc
  "refreshToken": "924df9ee-516a-4f6f-94d5-09a5efa5a09b
@refresh_token = 254654ec-8e6d-489c-83d1-fbd983133fee


### [1] Get All Timer Records
GET {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

###

### [2] Create a Timer Record
POST {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_id": 1,
  "date": "2025-05-15",
  "timer_duration": 3600
}

###

### [3] Get Timer Records for Non-Existent User
GET {{baseUrl}}/api/timers
Authorization: Bearer {{invalid_access_token}}
Content-Type: application/json

###

### [4] Create Timer Record with Missing Fields
POST {{baseUrl}}/api/timers
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "user_id": 1,
  "date": "2025-05-10"
}

###

### [5] Create Timer Record for Unauthorized User
POST {{baseUrl}}/api/timer
Authorization: Bearer {{invalid_access_token}}
Content-Type: application/json

{
  "user_id": 999,
  "date": "2025-05-10",
  "timer_duration": 3600
}